### ISSUE TITLE
Use github actions to automate pulling results from danlisa

### ISSUE THREAD

**Issue by rickselby** [mondaynightskippys/mondaynightskippys.github.io#91]
It should be possible to schedule a workflow to run the fetch_danlisa.rb script daily and create a pull request automatically if anything has changed. We would then only need to merge the pull requests and do a manual update once per season.

**Comment by d4rr3ll** [comment]
Nice one.  That was the thing that was missing when this was originally put together.  I'm not sure if workflows were a thing then or I simply didn't know about them.
